services:
  api_prediction:
    build: .
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - db
    networks:
      - mynetwork
    ports:
      - "5000:5000"
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - ./datasets/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./datasets/extract-by-day.csv:/datasets/extract-by-day.csv
      - my-db:/var/lib/postgresql/data
    networks:
      - mynetwork

volumes:
  my-db:
networks:
  mynetwork:
    driver: bridge
